language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - mongodb

before_script:
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b master
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && sudo make install && phpenv config-add ../unit-tests/ci/phalcon.ini)
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - cp tests/config.php.sample tests/config.php

script:
  - php vendor/bin/phpunit -c tests/phpunit.xml